PACKAGE_NAME="rpi5-ili9341"
PACKAGE_VERSION="1.0.0"
BUILT_MODULE_NAME[0]="rpi5_ili9341"
DEST_MODULE_LOCATION[0]="/extra"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build module"
CLEAN="make clean"
AUTOINSTALL="yes"
